[[redirects]]
  from = "/zoom"
  to = "https://us02web.zoom.us/j/87214043821?pwd=K3J3bk9CNDFsdlI2ZCtuOGxCL2FzZz09"
  status = 302
[[redirects]]
  from = "/rambly"
  to = "https://ramb.ly/spec.la"
  status = 302
